AWSTemplateFormatVersion: '2010-09-09'
Description: A starter AWS Lambda function
Resources:
  Table:
    Properties:
      PrimaryKey:
        Name: greeting
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
    Type: AWS::Serverless::SimpleTable
  helloworldpython3:
    Properties:
      CodeUri: s3://citrus-code-sam/777faf673aa9624849957d2668a775d2
      Description: A starter AWS Lambda function
      Environment:
        Variables:
          REGION_NAME:
            Ref: AWS::Region
          TABLE_NAME:
            Ref: Table
      Events:
        HelloWorldSAMAPI:
          Properties:
            Method: ANY
            Path: /hello
          Type: Api
      Handler: app.lambda_handler
      MemorySize: 128
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: Table
      Runtime: python3.6
      Timeout: 10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
